#!/bin/sh

set -eu

python3 -m CoverageTestRunner --ignore-missing-from=without-tests yarns vmdb

yarn \
    --shell=python3 \
    --shell-arg '' \
    --shell-library yarns/lib.py \
    --env "PYTHONPATH=$(pwd)/yarns" \
    --cd-datadir \
    yarns/*.yarn "$@"
