#!/bin/bash

set -eu

amd64_tarball="$1"
shift
arm64_tarball="$1"
shift

tryit()
{
    local image="$1"
    local yaml="$2"
    local tarball="$3"

    echo "Testing $yaml"
    ./vmdb2 --rootfs-tarball "$dst/$tarball" \
            --verbose \
            --log "$dst/check.log" \
            --output "$image" \
            "$yaml"
    echo
}

src="$(dirname "$0")"
dst="$(pwd)"
cd "$src"

#tryit luks.img "$src/luks.vmdb"
#tryit lvm2.img "$src/lvm2.vmdb"; exit

./smoke.sh "$amd64_tarball"

for x in "$@" pc uefi ansible smoke-pc smoke-uefi
do
    tryit "$dst/$x.img" "$x.vmdb" "$amd64_tarball"
done

for x in "$@" arm64-uefi
do
    tryit "$dst/$x.img" "$x.vmdb" "$arm64_tarball"
done

echo All test images built successfully.
