.\" Copyright 2017 Lars Wirzenius <liw@liw.fi>
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.TH VMDB2 1
.SH NAME
vmdb2 \- create a disk image with Debian installed
.SH SYNOPSIS
.nh
.B vmdb2
.RB [ \-\-image\fR=\fIFILE ]
.RB [ \-\-output\fR=\fIFILE ]
.RB [ \-\-rootfs\-tarball\fR=\fIFILE ]
.RB [ \-h | \-\-help ]
.RB [ \-\-version ]
.RB [ \-v | \-\-verbose ]
.RB [ \-\-log\fR=\fIFILE ]
.RI [ FILE ]... ""
.hy
.B vmdb
.IR SPECFILE
.SH DESCRIPTION
.B vmdb2
reads a
.I "specification file"
that describes a disk image,
and builds the corresponding image.
The specification file uses YAML syntax,
and contains a list of steps.
Each step tells vmdb2 what to do next.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
show this help message and exit
.TP
.BR \-\-image =\fIFILE
use existing image file/device
.I FILE
.TP
.BR \-\-output =\fIFILE
create new image
.I FILE
(the size comes from the specification file)
.TP
.BR \-\-rootfs\-tarball =\fIFILE
store rootfs cache tar archives in
.I FILE
.TP
.BR \-v ", " \-\-verbose
verbose output
.TP
.BR \-\-log =\fIFILE
write log entries to
.I FILE
(default is to not write log files at all)
.TP
.BR \-\-version
show program's version number and exit
.SH EXAMPLE
To build a disk image:
.PP
.nf
.RS
vmdb2 foo.vmdb --output foo.img -v --rootfs-tarball foo.tar.gz
.RE
.fi
.SH "SEE ALSO"
.BR debootstrap (8).
.PP
.I https://vmdb2.liw.fi/
.PP
.IR /usr/share/doc/vmdb2/manual.html
